# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
arry = np.random.rand(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
arry1 = np.arange(10, 49)

4. Find the shape of previous array in question 3

In [4]:
arry1.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
arry1.dtype

dtype('int32')

6. Print the dimension of the array in question 3


In [6]:
arry1.ndim

1

7. Create a boolean array with all the True values

In [7]:
arryb = np.arange(10)
arryb2 = np.arange(10)
arryb == arryb2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

8. Create a two dimensional array




In [8]:
arry2d = np.array([[0, 2, 3],[4, 5, 6]])

9. Create a three dimensional array



In [9]:
arry3d = np.array([[[0, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last) <br> hint: Read About Flip In Numpy

In [10]:
arry3d[::-1]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 0,  2,  3],
        [ 4,  5,  6]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [11]:
array3 = np.zeros(10)
array3[4] = 1

13. Create a 3x3 identity matrix (hint: Read About Identity Function Of Numpy)

In [12]:
array_2D = np.identity(3)


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [13]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype(np.float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [14]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 * arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array of maximum values by comparing both the arrays provided above 

In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.maximum(arr1, arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [16]:
arr_o = np.arange(9)
arr_o [arr_o % 2 == 1]

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array (hint: Read About Numpy Where Function)

In [17]:
arr_o = np.arange(9)
arr_c = arr_o [arr_o % 2 == 1]
arr_c[:] = -1

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [18]:
arr = np.arange(10)
arr[5:9] = 12

20. Create a 2d array with 1 on the border and 0 inside

In [19]:
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [20]:
arr2ds = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2ds[1,1] = 12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [21]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [22]:
arr = np.arange(9).reshape(3,3)
arr_te = arr[0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [23]:
arr = np.arange(9).reshape(3,3)
arr_tem = arr[1]

25. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
arrm = np.random.rand(10,10)
print('Maximum', arrm.max())
print('Minimum', arrm.min())

Maximum 0.9901658403708303
Minimum 0.007610360426423046


26. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


27.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [26]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Will"]

array([[-0.9040723 ,  0.09058987,  0.41728625, -1.10847593],
       [-0.43968257, -0.23918775,  0.80185966,  0.30085563],
       [-0.20365875, -0.04195881,  1.68152649, -1.47958579],
       [ 0.34893235, -1.12523194,  0.28997267, -0.06739176],
       [ 1.1602098 , -1.62729147, -0.19088808,  0.47369873]])

28. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != "Joe"]
data[names != "Will"]

array([[-0.12593405,  0.57092623,  1.72759118,  0.4283817 ],
       [ 1.49040095,  0.9020507 ,  1.36522594, -0.15115344],
       [ 0.40659489,  0.27088523, -2.43846035, -0.9621589 ],
       [ 0.24022537, -0.13750029, -0.06518592, -0.73890154],
       [-0.71835294,  0.8040613 , -0.74454239,  2.04363693]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [28]:
arry2 = np.arange(15).reshape(5, 3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
arry3 = np.arange(16).reshape(2,2,4)

33. Swap axes of the array you created in Question 32

In [30]:
arry3.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
arr20 = np.random.rand(12)
arr21 = np.random.rand(12)
np.maximum(arr20, arr21)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names1 = np.array(['Bobs', 'Joes', 'Will', 'Bob', 'Wills', 'Joes', 'Joe'])
np.union1d(names, names1)

38. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

39. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
arr3d = np.arange(2,10)
arr2d = np.cumsum(arr3d)